### ISSUE TITLE
dataset names not accepted

### ISSUE THREAD

**Issue by spamferkel** [ClusterHQ/pyzfs#26]
Hi,
i was  playing around with pyzfs and noticed this:

`Python 3.3.5 (default, Mar  9 2016, 01:03:10)`
`[GCC 4.9.3] on linux`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import libzfs_core`
`>>> libzfs_core.lzc_list_snaps(bytes('pool/dataset', 'utf-8'))`
`Traceback (most recent call last):`
`File "<stdin>", line 1, in <module>`
`File "/usr/lib64/python3.3/site-packages/libzfs_core/_libzfs_core.py", line 722, in _f`
`return func(*args, **kwargs)`
`File "/usr/lib64/python3.3/site-packages/libzfs_core/_libzfs_core.py", line 1077, in lzc_list_snaps`
`for entry in _list(name, recurse=1, types=['snapshot']):`
`File "/usr/lib64/python3.3/site-packages/libzfs_core/_libzfs_core.py", line 948, in _list`
`(fd, other_fd) = lzc_list(name, options)`
`File "/usr/lib64/python3.3/site-packages/libzfs_core/_libzfs_core.py", line 722, in _f`
`return func(*args, **kwargs)`
`File "/usr/lib64/python3.3/site-packages/libzfs_core/_libzfs_core.py", line 906, in lzc_list`
`opts_nv = nvlist_in(options)`
`File "/usr/lib64/python3.3/site-packages/libzfs_core/_nvlist.py", line 58, in nvlist_in`
`_dict_to_nvlist(props, nvlist)`
`File "/usr/lib64/python3.3/site-packages/libzfs_core/_nvlist.py", line 233, in _dict_to_nvlist`
`raise TypeError('Unsupported key type ' + type(k).__name__)`
`TypeError: Unsupported key type str`

`# pip show pyzfs`
`---`
`Metadata-Version: 1.1`
`Name: pyzfs`
`Version: 0.2.2`
`Summary: Wrapper for libzfs_core`
`Home-page: http://pyzfs.readthedocs.org`
`Author: ClusterHQ`
`Author-email: support@clusterhq.com`
`License: Apache License, Version 2.0`
`Location: /usr/lib64/python3.3/site-packages`
`Requires: cffi`

Is my call of `lzc_list_snaps` incorrect or is this a bug?

**Comment by avg-I** [comment]
That's a consequence of not caring about Python 3 compatibility when writing libzfs_core code.
So, you can consider it a missing feature. Python 3 is not supported.  Only Python 2.7.

**Comment by spamferkel** [comment]
it works under python2.7. Thx
