### ISSUE TITLE
Project NO LONGER MAINTAINED

### ISSUE THREAD

**Issue by yihuaf** [ClusterHQ/pyzfs#34]
Unfortunately, this project is no longer maintained and no one has write access to this repo any more. The code has moved to: https://github.com/zfsonlinux/zfs/tree/master/contrib/pyzfs

**Comment by glibg10b** [comment]
Why was this issue closed? Is its purpose not to serve as a public announcement?

**Comment by yihuaf** [comment]
> Why was this issue closed? Is its purpose not to serve as a public announcement?

No particular reason. Yes, the purpose is to serve as a public announcement. Closed issue also serves that purpose :)
